version: "3"
services:
    api:
        container_name: fusenemix-api
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        image: fusenemix-api
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${APP_PORT:-8000}:80"
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
        volumes:
            - ".:/var/www/html"
        networks:
            - fusenemix
        depends_on:
            - mysql
            - redis
            - meilisearch
            - minio
            - mailpit
    mysql:
        container_name: fusenemix-mysql
        image: "mysql/mysql-server:8.0"
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - "fusenemix-mysql:/var/lib/mysql"
            - "./vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
        networks:
            - fusenemix
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - "-p${DB_PASSWORD}"
            retries: 3
            timeout: 5s
    redis:
        container_name: fusenemix-redis
        image: "redis:alpine"
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - "fusenemix-redis:/data"
        networks:
            - fusenemix
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    meilisearch:
        container_name: fusenemix-meilisearch
        image: "getmeili/meilisearch:latest"
        ports:
            - "${FORWARD_MEILISEARCH_PORT:-7700}:7700"
        volumes:
            - "fusenemix-meilisearch:/meili_data"
        networks:
            - fusenemix
        healthcheck:
            test:
                - CMD
                - wget
                - "--no-verbose"
                - "--spider"
                - "http://localhost:7700/health"
            retries: 3
            timeout: 5s
    minio:
        container_name: fusenemix-minio
        image: "minio/minio:latest"
        ports:
            - "${FORWARD_MINIO_PORT:-9000}:9000"
            - "${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900"
        environment:
            MINIO_ROOT_USER: fusenemix
            MINIO_ROOT_PASSWORD: password
        volumes:
            - "fusenemix-minio:/data/minio"
        networks:
            - fusenemix
        command: 'minio server /data/minio --console-address ":8900"'
        healthcheck:
            test:
                - CMD
                - curl
                - "-f"
                - "http://localhost:9000/minio/health/live"
            retries: 3
            timeout: 5s
    mailpit:
        container_name: fusenemix-mailpit
        image: "axllent/mailpit:latest"
        ports:
            - "${FORWARD_MAILPIT_PORT:-1025}:1025"
            - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
        networks:
            - fusenemix
    soketi:
        container_name: fusenemix-soketi
        image: "quay.io/soketi/soketi:latest-16-alpine"
        environment:
            SOKETI_DEBUG: "1"
            SOKETI_METRICS_SERVER_PORT: "9601"
        ports:
            - "${SOKETI_PORT:-6001}:6001"
            - "${SOKETI_METRICS_SERVER_PORT:-9601}:9601"
        networks:
            - fusenemix
networks:
    fusenemix:
        driver: bridge
volumes:
    fusenemix-mysql:
        driver: local
    fusenemix-redis:
        driver: local
    fusenemix-meilisearch:
        driver: local
    fusenemix-minio:
        driver: local
