name: develop

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  api:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
    services:
      fusenemix-mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_HOST: "%"
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
          MYSQL_USER: fusenemix
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"
      - uses: actions/checkout@v2
      - name: Cache apt packages
        uses: actions/cache@v2
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('**/apt.lock') }}
          restore-keys: ${{ runner.os }}-apt-
      - name: Install apt dependencies
        run: sudo apt-get install -y ffmpeg
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        working-directory: api
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --prefer-dist
        working-directory: api
      - name: Generate key
        run: php artisan key:generate
        working-directory: api
      - name: Generate JWT Secret
        run: php artisan jwt:secret -f
        working-directory: api
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        working-directory: api
      - name: Execute tests (Unit and Feature tests) via PestPHP
        run: php artisan test --coverage
        working-directory: api
