name: develop

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 16.x]
    env:
      DEBIAN_FRONTEND: noninteractive
    services:
      fusenemix-mysql:
        image: mysql/mysql-server:8.0
        env:
          MYSQL_ROOT_HOST: "%"
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_DATABASE: testing
          MYSQL_USER: fusenemix
          MYSQL_PASSWORD: password
        ports:
          - "${DB_PORT:-3306}:3306"
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      fusenemix-redis:
        image: redis:alpine
        ports:
          - "${REDIS_PORT:-6379}:6379"

    steps:
      - uses: actions/checkout@v2
      - name: Install apt dependencies
        run: sudo apt-get install -y ffmpeg
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Copy .env
        run: cp .env.testing .env
        working-directory: api
      - name: Install Dependencies
        run: npm install
        working-directory: api
      - name: Check build
        run: npm run build:check
        working-directory: api
      - name: Migrate database
        run: npm run migrate
        working-directory: api
      - name: Seed database
        run: npm run seed
        working-directory: api
      - name: Run linter
        run: npm run lint
        working-directory: api
      - name: Check formatting
        run: npm run format:check
        working-directory: api
      - name: Run tests
        run: npm run test
        working-directory: api
